whitelist:
  - address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"  # WETH
    symbol: WETH
  - address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"  # USDC
    symbol: USDC

blacklist:
  - "0x123...abc"  # Known scam token
  - "0x456...def"  # Low liquidity token
